# Generated by Django 4.1 on 2023-08-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_remove_hourlygoals_monthly_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyHourDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='hourlygoals',
            name='weekly_hours',
            field=models.IntegerField(default=1),
        ),
    ]
